import { useState } from 'react'
import { ClipboardCheck, GitBranch, RefreshCw, CheckCircle } from 'lucide-react'
import { Plan, pipelineApi } from '../services/api'
import { fmtDateTime } from '../utils/time'
import PlanContent from '../components/PlanContent'

interface Props {
  runId: string
  plan: Plan
  onAction: () => void
}

export default function PlanReview({ runId, plan, onAction }: Props) {
  const [edits, setEdits] = useState('')
  const [feedback, setFeedback] = useState('')
  const [loading, setLoading] = useState(false)
  const [showNotes, setShowNotes] = useState(false)
  const [showRejectForm, setShowRejectForm] = useState(false)

  const handleApprove = async () => {
    setLoading(true)
    try {
      await pipelineApi.approvePlan(runId, edits ? { user_edits: edits } : undefined)
      onAction()
    } finally {
      setLoading(false)
    }
  }

  const handleReplan = async () => {
    if (!feedback.trim()) return
    setLoading(true)
    try {
      await pipelineApi.replan(runId, feedback)
      onAction()
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="rounded-xl border bg-white overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between px-5 py-4 border-b bg-orange-50">
        <div className="flex items-center gap-2">
          <ClipboardCheck className="h-4 w-4 text-orange-600" />
          <div>
            <p className="font-semibold text-gray-900 text-sm">Implementation Plan — Ready for Review</p>
            <p className="text-xs text-gray-500 mt-0.5">
              Version {plan.version} · Generated by Claude ·{' '}
              {fmtDateTime(plan.created_at)}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-1.5">
          <span className="inline-flex items-center gap-1 rounded-full bg-orange-100 px-2 py-0.5 text-xs font-medium text-orange-700">
            <span className="h-1.5 w-1.5 rounded-full bg-orange-500 animate-pulse" />
            Awaiting approval
          </span>
        </div>
      </div>

      {/* Plan content */}
      <div className="px-5 py-5">
        <PlanContent content={plan.content} />
      </div>

      {/* Optional: add notes before approving */}
      {!showRejectForm && (
        <div className="px-5 pb-2">
          <button
            onClick={() => setShowNotes((s) => !s)}
            className="text-xs text-gray-500 hover:text-gray-700 underline underline-offset-2"
          >
            {showNotes ? 'Hide notes' : '+ Add notes for Claude (sent alongside approval)'}
          </button>
          {showNotes && (
            <textarea
              className="mt-2 w-full rounded-lg border px-3 py-2 text-sm resize-none"
              value={edits}
              onChange={(e) => setEdits(e.target.value)}
              rows={3}
              placeholder="e.g., Also add rate limiting to the endpoint, use PostgreSQL not SQLite..."
            />
          )}
        </div>
      )}

      {/* Request changes form */}
      {showRejectForm && (
        <div className="mx-5 mb-4 rounded-lg bg-amber-50 border border-amber-200 p-4">
          <p className="text-sm font-medium text-amber-800 mb-2">
            <RefreshCw className="inline h-3.5 w-3.5 mr-1" />
            Request a replan
          </p>
          <p className="text-xs text-amber-700 mb-2">
            Describe what's missing or wrong — Claude will generate a new plan.
          </p>
          <textarea
            className="w-full rounded-lg border border-amber-300 bg-white px-3 py-2 text-sm resize-none"
            value={feedback}
            onChange={(e) => setFeedback(e.target.value)}
            rows={3}
            autoFocus
            placeholder="e.g., The plan doesn't account for mobile responsiveness. Also add pagination..."
          />
          <div className="flex gap-2 mt-3">
            <button
              onClick={() => { setShowRejectForm(false); setFeedback('') }}
              className="text-sm text-gray-500 hover:text-gray-700"
            >
              Cancel
            </button>
            <button
              onClick={handleReplan}
              disabled={!feedback.trim() || loading}
              className="flex items-center gap-1.5 rounded-lg bg-amber-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-amber-700 disabled:opacity-50"
            >
              {loading ? (
                <RefreshCw className="h-3 w-3 animate-spin" />
              ) : (
                <RefreshCw className="h-3 w-3" />
              )}
              {loading ? 'Sending...' : 'Request Replan'}
            </button>
          </div>
        </div>
      )}

      {/* Action bar */}
      <div className="flex gap-2 px-5 py-4 border-t bg-gray-50">
        {!showRejectForm && (
          <button
            onClick={() => { setShowRejectForm(true); setShowNotes(false) }}
            className="flex items-center gap-1.5 rounded-lg border border-gray-300 px-4 py-2 text-sm text-gray-600 hover:bg-white"
          >
            <GitBranch className="h-3.5 w-3.5" />
            Request Changes
          </button>
        )}
        <button
          onClick={handleApprove}
          disabled={loading}
          className="flex flex-1 items-center justify-center gap-1.5 rounded-lg bg-green-600 px-4 py-2 text-sm font-medium text-white hover:bg-green-700 disabled:opacity-50"
        >
          {loading ? (
            <RefreshCw className="h-4 w-4 animate-spin" />
          ) : (
            <CheckCircle className="h-4 w-4" />
          )}
          {loading ? 'Approving...' : 'Approve & Start Development'}
        </button>
      </div>
    </div>
  )
}
