import re
from app.agents.base import BaseAgent, AgentResult
from app.services.gitlab_service import GitLabService
from app.services import github_service


def _fix_branding(text: str) -> str:
    """Replace 'AILegal' (word boundary) with 'AI Legal'."""
    return re.sub(r'\bAILegal\b', 'AI Legal', text)


class PRCreatorAgent(BaseAgent):
    agent_type = "pr_creator"

    async def run(
        self,
        feature_branch: str,
        base_branch: str,
        task_title: str,
        task_description: str,
        plan_content: str,
        pr_checklist: list,
        # Legacy GitLab fields (still supported)
        gitlab_repo_url: str = "",
        gitlab_project_id: str = "",
        gitlab_token: str = "",
        # New provider-agnostic fields
        git_provider: str | None = None,
        repo_full_name: str = "",
        git_token: str = "",
        project_dir: str = "/tmp",
        task_number: str = "",
        test_scenarios: list | None = None,
        db=None,
    ) -> AgentResult:
        if db:
            await self._create_agent_run(db)

        self.publish_log(f"[PRCreator] Creating PR/MR: {feature_branch} → {base_branch}")

        # Normalise branding in user-visible text
        task_title = _fix_branding(task_title)
        task_description = _fix_branding(task_description)
        plan_content = _fix_branding(plan_content)

        # Build description
        checklist_items = "\n".join([f"- [ ] {item}" for item in (pr_checklist or [])])

        test_section = ""
        if test_scenarios:
            passed = sum(1 for s in test_scenarios if s.get("status") == "passed")
            failed = sum(1 for s in test_scenarios if s.get("status") == "failed")
            total = len(test_scenarios)
            rows = []
            for s in test_scenarios:
                icon = "✅" if s.get("status") == "passed" else "❌" if s.get("status") == "failed" else "⏸️"
                name = s.get("name", "")
                steps = s.get("steps", "")
                expected = s.get("expected", "")
                detail = []
                if steps:
                    detail.append(f"Steps: {steps}")
                if expected:
                    detail.append(f"Expected: {expected}")
                detail_str = " | ".join(detail) if detail else "—"
                rows.append(f"| {icon} | {name} | {detail_str} |")

            test_section = f"""
## Test Results
**{passed}/{total} passed** · {failed} failed

| Status | Test Case | Details |
|--------|-----------|---------|
{chr(10).join(rows)}
"""

        description = f"""## Task
{task_title}

## Description
{task_description}

## Implementation Summary
{plan_content[:1000]}...
{test_section}
## Checklist
{checklist_items or "- [ ] Code reviewed\n- [ ] Tests pass\n- [ ] Documentation updated"}

---
*Auto-generated by AutoDev*"""

        # Determine effective provider
        effective_provider = git_provider
        if not effective_provider:
            if gitlab_repo_url or gitlab_project_id:
                effective_provider = "gitlab"

        commit_msg = PRCreatorAgent.make_commit_message(task_title, task_number)

        try:
            if effective_provider == "github":
                return await self._create_github_pr(
                    feature_branch=feature_branch,
                    base_branch=base_branch,
                    task_title=task_title,
                    description=description,
                    git_token=git_token,
                    repo_full_name=repo_full_name,
                    project_dir=project_dir,
                    commit_message=commit_msg,
                    db=db,
                )
            else:
                # Default to GitLab (legacy)
                return await self._create_gitlab_mr(
                    feature_branch=feature_branch,
                    base_branch=base_branch,
                    task_title=task_title,
                    description=description,
                    gitlab_repo_url=gitlab_repo_url,
                    gitlab_project_id=gitlab_project_id,
                    gitlab_token=gitlab_token or git_token,
                    db=db,
                )

        except Exception as e:
            error = str(e)
            self.publish_log(f"[PRCreator] ERROR: {error}")
            if db:
                await self._record_agent_run(db, "failed", "", error, exit_code=1)
            return AgentResult(success=False, error=error, exit_code=1)

    async def _create_github_pr(
        self,
        feature_branch: str,
        base_branch: str,
        task_title: str,
        description: str,
        git_token: str,
        repo_full_name: str,
        project_dir: str,
        commit_message: str = "",
        db=None,
    ) -> AgentResult:
        # Push the branch first (checkout from base_branch)
        # Tests approved — now commit all changes, push the branch, then create PR.
        self.publish_log(f"[PRCreator] Committing and pushing branch {feature_branch} → {base_branch} …")
        success, msg = await github_service.push_branch(
            project_dir=project_dir,
            branch_name=feature_branch,
            token=git_token,
            repo_full_name=repo_full_name,
            base_branch=base_branch,
            commit_message=commit_message,
        )
        if not success:
            raise RuntimeError(f"Push failed: {msg}")
        self.publish_log(f"[PRCreator] Push result: {msg}")

        # Parse owner / repo
        parts = repo_full_name.split("/", 1)
        if len(parts) != 2:
            raise ValueError(f"Invalid repo_full_name: {repo_full_name!r} — expected owner/repo")
        owner, repo = parts

        # Create PR
        pr_data = await github_service.create_pull_request(
            token=git_token,
            owner=owner,
            repo=repo,
            title=f"[AutoDev] {task_title}",
            body=description,
            head=feature_branch,
            base=base_branch,
        )

        pr_url = pr_data.get("html_url", "")
        pr_number = str(pr_data.get("number", ""))
        actual_base = pr_data.get("base", {}).get("ref", base_branch)  # actual branch GitHub used
        self.publish_log(f"[PRCreator] PR created: {pr_url} ({feature_branch} → {actual_base})")

        if db:
            await self._record_agent_run(db, "completed", f"PR created: {pr_url}", exit_code=0)

        return AgentResult(
            success=True,
            output=f"MR created: {pr_url}\nMR ID: {pr_number}\nBase branch: {actual_base}",
            exit_code=0,
        )

    async def _create_gitlab_mr(
        self,
        feature_branch: str,
        base_branch: str,
        task_title: str,
        description: str,
        gitlab_repo_url: str,
        gitlab_project_id: str,
        gitlab_token: str,
        db,
    ) -> AgentResult:
        service = GitLabService(gitlab_repo_url, gitlab_token, gitlab_project_id)
        mr_data = await service.create_merge_request(
            source_branch=feature_branch,
            target_branch=base_branch,
            title=f"[AutoDev] {task_title}",
            description=description,
        )

        mr_url = mr_data.get("web_url", "")
        mr_id = str(mr_data.get("iid", ""))
        self.publish_log(f"[PRCreator] MR created: {mr_url}")

        if db:
            await self._record_agent_run(db, "completed", f"MR created: {mr_url}", exit_code=0)

        return AgentResult(
            success=True,
            output=f"MR created: {mr_url}\nMR ID: {mr_id}",
            exit_code=0,
        )

    @staticmethod
    def make_branch_name(task_id: str, task_title: str, task_number: str = "") -> str:
        if task_number:
            safe_num = re.sub(r"[^a-zA-Z0-9\-_]", "-", task_number).strip("-")
            slug = re.sub(r"[^a-zA-Z0-9]+", "-", task_title.lower())[:40].strip("-")
            return f"autodev/{safe_num}-{slug}" if slug else f"autodev/{safe_num}"
        safe_id = re.sub(r"[^a-zA-Z0-9\-_.]", "-", task_id)
        return f"autodev/{safe_id}"

    @staticmethod
    def make_commit_message(task_title: str, task_number: str = "") -> str:
        title = re.sub(r'\bAILegal\b', 'AI Legal', task_title)
        if task_number:
            return f"ZOHO #{task_number}: {title}"
        return f"[AutoDev] {title}"
